#pragma once

enum ShaderStage
{
	VERTEX_SHADER_STAGE = 1,
	FRAGMENT_SHADER_STAGE,
	GEOMETRY_SHADER_STAGE = 4,
	TESS_CONTROL_SHADER_STAGE = 8,
	TESS_EVALUATION_SHADER_STAGE = 16,
	COMPUTE_SHADER_STAGE = 32
};