#pragma once

enum ShaderStatus
{
	ACTIVE_UNIFORM_BLOCKS = 35382,
	SHADER_TYPE = 35663,
	DELETE_STATUS = 35712,
	COMPILE_STATUS,
	LINK_STATUS,
	INFO_LOG_LENGTH = 35716,
	ATTACHED_SHADERS,
	ACTIVE_UNIFORMS,
	SHADER_SOURCE_LENGTH = 35720,
	ACTIVE_ATTRIBUTES
};